"""Regenerate ``SKILLS_INDEX.yaml`` from the four-layer skill tree.

Walks ``easybci_lib/skills/bci/`` and emits a YAML index organised by
``layer / group / name``. Run after any change to skill frontmatter or
directory layout so the YAML stays in sync with disk.

Gated by ``_check_consistency.py --strict``: if any consistency rule fails,
the regenerator refuses to write a possibly-misleading index.

Usage::

    python -m easybci_lib.tools.neural_processing.regen_skills_index
        [--root easybci_lib/skills/bci]
        [--out  easybci_lib/tools/neural_processing/SKILLS_INDEX.yaml]
        [--skip-strict-check]   # for development only
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any, Dict, List

import yaml

from easybci_lib.tools.neural_processing._check_consistency import (
    check as run_consistency_check,
)
from easybci_lib.tools.neural_processing.skill_layers import (
    GROUPS_BY_LAYER,
    LAYERS,
)


_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _read_frontmatter(path: Path) -> Dict[str, Any]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return {}
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return {}
    return fm if isinstance(fm, dict) else {}


def _layer_for_skill(rel: Path, fm: Dict[str, Any]) -> str | None:
    layer = fm.get("layer")
    if layer in LAYERS:
        return layer
    # Fallback: infer from path (shouldn't happen post-migration)
    parts = rel.parts
    if not parts:
        return None
    head = parts[0]
    return {
        "neural-io": "L0",
        "pipeline": "L1",
        "paradigms": "L2",
        "operators": "L3",
    }.get(head)


def _group_for_skill(fm: Dict[str, Any], layer: str | None) -> str:
    group = fm.get("group")
    if isinstance(group, str) and group:
        return group
    if layer == "L1":
        return "(orchestration)"
    return "misc"


def build_index(root: Path) -> Dict[str, Any]:
    layers: Dict[str, Dict[str, List[Dict[str, str]]]] = {
        layer: {} for layer in LAYERS
    }
    excluded_dirs = {".git", ".github", ".hub", ".archive", "scripts"}
    for path in sorted(root.rglob("*.md")):
        if any(part in excluded_dirs for part in path.parts):
            continue
        if path.name in ("DESCRIPTION.md", "CODE_STANDARD.md"):
            continue
        rel = path.relative_to(root)
        if not rel.parts or rel.parts[0] not in (
            "neural-io", "pipeline", "paradigms", "operators",
        ):
            continue
        if path.name != "SKILL.md" and rel.parts[0] not in ("paradigms",):
            continue
        fm = _read_frontmatter(path)
        layer = _layer_for_skill(rel, fm)
        if layer is None:
            continue
        group = _group_for_skill(fm, layer)
        entry: Dict[str, str] = {
            "name": fm.get("name", path.stem if path.name != "SKILL.md" else path.parent.name),
            "description": fm.get("description", ""),
            "path": str(rel),
        }
        md = fm.get("metadata") or {}
        if isinstance(md, dict):
            step_string = md.get("step_string")
            modalities = md.get("modalities")
            if step_string:
                entry["step_string"] = step_string
            if modalities:
                entry["modalities"] = modalities
        layers[layer].setdefault(group, []).append(entry)

    # Sort groups by their declared enum order, then unknown groups alphabetically
    out_layers: Dict[str, Dict[str, List[Dict[str, str]]]] = {}
    for layer in LAYERS:
        enum_order = GROUPS_BY_LAYER.get(layer, []) or []
        known = [g for g in enum_order if g in layers[layer]]
        extra = sorted(g for g in layers[layer] if g not in enum_order)
        ordered: Dict[str, List[Dict[str, str]]] = {}
        for g in known + extra:
            entries = sorted(layers[layer][g], key=lambda x: x["name"])
            ordered[g] = entries
        if ordered:
            out_layers[layer] = ordered

    return {
        "version": "2.0",
        "description": (
            "BCI four-layer skill index — regenerated by `regen_skills_index.py` "
            "from `easybci_lib/skills/bci/`. Do not hand-edit."
        ),
        "layers": out_layers,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="regen_skills_index",
        description="Regenerate SKILLS_INDEX.yaml from the four-layer skill tree (T9 1-6).",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path("easybci_lib/skills/bci"),
        help="Root of the bci skill tree (default: easybci_lib/skills/bci)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("easybci_lib/tools/neural_processing/SKILLS_INDEX.yaml"),
        help="Output YAML path",
    )
    parser.add_argument(
        "--skip-strict-check",
        action="store_true",
        help="Skip the consistency check gate (development only)",
    )
    args = parser.parse_args(argv)

    root = args.root.resolve()
    if not root.exists():
        print(f"root not found: {root}", file=sys.stderr)
        return 2

    if not args.skip_strict_check:
        findings = run_consistency_check(root)
        fails = [f for f in findings if f.severity == "fail"]
        if fails:
            print(
                f"refused: {len(fails)} consistency FAIL(s). "
                "Run `_check_consistency.py --strict` to inspect; pass "
                "`--skip-strict-check` to override (dev only).",
                file=sys.stderr,
            )
            return 1

    index = build_index(root)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        yaml.dump(index, sort_keys=False, allow_unicode=True, default_flow_style=False),
        encoding="utf-8",
    )

    total = sum(
        len(entries)
        for groups in index["layers"].values()
        for entries in groups.values()
    )
    by_layer = {layer: sum(len(es) for es in groups.values()) for layer, groups in index["layers"].items()}
    print(f"Wrote {args.out} — {total} skills.")
    for layer, n in by_layer.items():
        if n:
            print(f"  {layer}: {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
