"""Skill Writer — interactive creation of new preprocessing skills.

Implements the conversation protocol for authoring new skills:
1. Agent generates skill code based on user description
2. Code is validated in a sandbox (subprocess execution with test data)
3. User reviews and confirms
4. Skill is persisted to disk and registered in the tool registry

The skill writing flow:
  describe → generate → sandbox_test → confirm → persist → register
"""

import datetime as _dt
import json
import logging
import os
import tempfile
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    from easybci_cli import config as _ebci_config  # type: ignore
except Exception:  # noqa: BLE001
    _ebci_config = None  # type: ignore[assignment]

logger = logging.getLogger(__name__)

SKILL_TEMPLATE = '''"""Skill: {name} — {description}

Auto-generated by EasyBCIdata skill writer.
Created: {created_at}

Input:  data_dict (dict with 'data' ndarray, 'frequency', 'channels', 'meta')
Output: data_dict (same structure, transformed)
"""

import numpy as np
from typing import Any, Dict


def {func_name}(data_dict: Dict[str, Any], {params_signature}) -> Dict[str, Any]:
    """{docstring}"""
    data = data_dict["data"]
    frequency = data_dict["frequency"]

{body}

    data_dict["data"] = data
    return data_dict


# Skill metadata for registration
SKILL_META = {{
    "name": "{name}",
    "description": "{description}",
    "category": "custom",
    "params": {params_json},
    "func_name": "{func_name}",
}}
'''

TEST_TEMPLATE = '''"""Auto-test for skill: {name}"""
import numpy as np
import sys
sys.path.insert(0, "{project_root}")

{skill_import}

# Generate synthetic test data
np.random.seed(42)
n_channels, n_samples = 8, 1024
test_data = {{
    "data": np.random.randn(n_channels, n_samples).astype(np.float32),
    "frequency": 256.0,
    "channels": [f"Ch{{i}}" for i in range(n_channels)],
    "duration": n_samples / 256.0,
    "meta": {{}},
}}

# Run the skill
result = {func_call}

# Validate output structure
assert isinstance(result, dict), "Must return a dict"
assert "data" in result, "Must contain 'data' key"
assert isinstance(result["data"], np.ndarray), "data must be ndarray"
assert result["data"].shape[0] == n_channels, f"Channel count mismatch: {{result['data'].shape[0]}} vs {{n_channels}}"
assert not np.any(np.isnan(result["data"])), "Output contains NaN"
assert not np.any(np.isinf(result["data"])), "Output contains Inf"

print("SKILL_TEST_PASSED")
print(f"Output shape: {{result['data'].shape}}")
print(f"Output dtype: {{result['data'].dtype}}")
'''


class SkillWriter:
    """Manages the lifecycle of creating new processing skills."""

    def __init__(self, skills_dir: Optional[str] = None):
        if skills_dir:
            self._skills_dir = Path(skills_dir)
        else:
            self._skills_dir = Path(__file__).parent / "custom"
        self._skills_dir.mkdir(parents=True, exist_ok=True)
        self._drafts: Dict[str, Dict[str, Any]] = {}

    def _collect_origin_metadata(self, *, cohort_tag: str = "") -> Dict[str, Any]:
        """Collect provenance frontmatter fields injected into proven-pipeline writebacks.

        Reads user.lab_id from ``easybci_cli.config.load_config()`` (the only
        legitimate config reader per CLAUDE.md). Empty / missing → ``"local"``.
        """
        cfg: Dict[str, Any] = {}
        if _ebci_config is not None:
            try:
                cfg = _ebci_config.load_config() or {}
            except Exception:  # noqa: BLE001
                cfg = {}
        lab_id = str(((cfg.get("user") or {}).get("lab_id") or "local"))
        return {
            "lab_id": lab_id,
            "origin_set": "",
            "contributed_at": _dt.datetime.utcnow().isoformat() + "Z",
            "cohort_tag": cohort_tag or "",
        }

    def generate_skill(
        self,
        name: str,
        description: str,
        body: str,
        params: Optional[Dict[str, str]] = None,
        docstring: str = "",
    ) -> Dict[str, Any]:
        """Generate skill source code from components.

        Returns dict with 'code', 'test_code', 'name', and draft metadata.
        """
        func_name = name.replace("-", "_").replace(" ", "_").lower()
        params = params or {}
        params_signature = ", ".join(f"{k}: {v}" for k, v in params.items()) if params else ""
        params_json = json.dumps(params)
        created_at = time.strftime("%Y-%m-%dT%H:%M:%S")

        code = SKILL_TEMPLATE.format(
            name=name,
            description=description,
            created_at=created_at,
            func_name=func_name,
            params_signature=params_signature,
            docstring=docstring or description,
            body=body,
            params_json=params_json,
        )

        project_root = str(Path(__file__).parent.parent)
        test_code = TEST_TEMPLATE.format(
            name=name,
            project_root=project_root,
            skill_import=f"from skill_draft import {func_name}",
            func_call=f"{func_name}(test_data{', ' + ', '.join(f'{k}={k}' for k in params) if params else ''})",
        )

        draft = {
            "name": name,
            "func_name": func_name,
            "description": description,
            "code": code,
            "test_code": test_code,
            "params": params,
            "created_at": created_at,
            "status": "draft",
        }
        self._drafts[name] = draft
        return draft

    def sandbox_test(self, name: str) -> Dict[str, Any]:
        """Test a draft skill in an isolated subprocess.

        Returns dict with 'success', 'stdout', 'stderr', 'duration'.
        """
        from easybci_lib.tools.neural_processing.executor.runner import execute_code

        draft = self._drafts.get(name)
        if not draft:
            return {"success": False, "error": f"No draft found: {name}"}

        # Write skill code and test to temp dir
        tmpdir = tempfile.mkdtemp(prefix="skill_sandbox_")
        skill_path = os.path.join(tmpdir, "skill_draft.py")
        test_path = os.path.join(tmpdir, "test_skill.py")

        with open(skill_path, "w", encoding="utf-8") as f:
            f.write(draft["code"])
        with open(test_path, "w", encoding="utf-8") as f:
            f.write(draft["test_code"])

        result = execute_code(
            code=draft["test_code"],
            timeout=30.0,
            working_dir=tmpdir,
        )

        passed = result.get("success", False) and "SKILL_TEST_PASSED" in result.get("stdout", "")
        result["test_passed"] = passed

        if passed:
            draft["status"] = "tested"
        else:
            draft["status"] = "test_failed"

        return result

    def persist_skill(self, name: str) -> Dict[str, Any]:
        """Save a tested skill to disk and register it.

        Only persists skills that passed sandbox testing.
        Writes to SKILLS_INDEX.yaml for auto-discovery on restart.
        """
        from easybci_lib.tools.neural_processing.skill_loader import save_to_index

        draft = self._drafts.get(name)
        if not draft:
            return {"success": False, "error": f"No draft found: {name}"}
        if draft["status"] not in ("tested", "confirmed"):
            return {"success": False, "error": f"Skill not tested/confirmed (status: {draft['status']})"}

        func_name = draft["func_name"]

        # Version handling: check if a previous version exists
        version = 1
        existing = list(self._skills_dir.glob(f"{func_name}*.py"))
        if existing:
            import re
            for f in existing:
                match = re.match(rf"^{func_name}(?:_v(\d+))?\.py$", f.name)
                if match:
                    v = int(match.group(1)) if match.group(1) else 1
                    version = max(version, v + 1)

        # Use versioned filename if not the first version
        if version > 1:
            skill_file = self._skills_dir / f"{func_name}_v{version}.py"
        else:
            skill_file = self._skills_dir / f"{func_name}.py"

        # Write skill file
        with open(skill_file, "w", encoding="utf-8") as f:
            f.write(draft["code"])

        # Register in tool registry (for current session)
        self._register_skill(draft, skill_file)

        # Persist to SKILLS_INDEX.yaml (for future sessions)
        save_to_index(draft, str(skill_file))

        # Generate documentation
        doc = self._generate_docs(draft)

        draft["status"] = "persisted"
        draft["file_path"] = str(skill_file)
        draft["version"] = version

        return {
            "success": True,
            "file_path": str(skill_file),
            "func_name": func_name,
            "version": version,
            "documentation": doc,
        }

    def confirm_skill(self, name: str) -> bool:
        """Mark a skill as confirmed by the user."""
        draft = self._drafts.get(name)
        if draft and draft["status"] == "tested":
            draft["status"] = "confirmed"
            return True
        return False

    def list_drafts(self) -> List[Dict[str, Any]]:
        """List all draft skills and their status."""
        return [
            {"name": d["name"], "status": d["status"], "description": d["description"]}
            for d in self._drafts.values()
        ]

    def list_custom_skills(self) -> List[Dict[str, str]]:
        """List all persisted custom skills."""
        skills = []
        for f in sorted(self._skills_dir.glob("*.py")):
            if f.name.startswith("_"):
                continue
            skills.append({"name": f.stem, "path": str(f)})
        return skills

    def _register_skill(self, draft: Dict[str, Any], skill_file: Path):
        """Register skill as a pipeline step in the registry."""
        from core.registry import registry

        func_name = draft["func_name"]
        name = draft["name"]
        description = draft["description"]
        params = draft.get("params", {})

        def _handler(data_path: str, modality: str = "auto", **kwargs) -> dict:
            """Dynamic handler for custom skill."""
            import importlib.util
            from easybci_lib.tools.neural_processing.io import load_neural

            spec = importlib.util.spec_from_file_location(func_name, str(skill_file))
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            skill_func = getattr(mod, func_name)

            data_dict = load_neural(data_path, modality=modality)
            result = skill_func(data_dict, **kwargs)
            return {
                "success": True,
                "data_shape": list(result["data"].shape),
                "frequency": result["frequency"],
                "channels": result.get("channels", []),
            }

        schema = {
            "type": "object",
            "properties": {
                "data_path": {"type": "string", "description": "Path to neural data file"},
                "modality": {"type": "string", "enum": ["auto", "eeg", "seeg", "ecog", "meg"]},
            },
            "required": ["data_path"],
        }
        for k, v in params.items():
            schema["properties"][k] = {"type": "string", "description": f"Parameter: {k}"}

        registry.register(
            name=f"custom_{func_name}",
            category="custom",
            description=f"[Custom] {description}",
            schema=schema,
            handler=_handler,
        )

    def _generate_docs(self, draft: Dict[str, Any]) -> str:
        """Generate documentation for a skill."""
        params = draft.get("params", {})
        params_doc = ""
        if params:
            params_doc = "\n**Parameters:**\n" + "\n".join(
                f"- `{k}` ({v})" for k, v in params.items()
            )

        doc = f"""## {draft['name']}

{draft['description']}

**Category:** custom
**Function:** `{draft['func_name']}`
**Created:** {draft['created_at']}
{params_doc}

**Usage in pipeline:**
```python
from easybci_lib.tools.neural_processing.custom.{draft['func_name']} import {draft['func_name']}

result = {draft['func_name']}(data_dict)
```

**Usage as tool:**
The skill is registered as `custom_{draft['func_name']}` in the tool registry.
"""
        return doc
